### ISSUE TITLE
Improve visibility of React and JS guides

### ISSUE THREAD

**Issue by mburridge** [frontity/docs#106]
He tried to find the React and JavaScript guides and he wasn't able to do so.

From: https://frontity.slack.com/archives/CD0NJS8L8/p1592377003003500

**Comment by juanmaguitar** [comment]
Oks, we'll take this into account but for now we've already agreed of placing all non-directly-frontity-related topic under the "Key Concepts" section

I would create a few blog posts regarding this to give this info a bit more visibility
