### ISSUE TITLE
Is Frontity compatible with page builders (like Elementor)?

### ISSUE THREAD

**Issue by juanmaguitar** [frontity/docs#126]
Hey, ...  asked me if Frontity is or plans to be compatible with page builders. I'd love to understand and learn more about this because I feel quite confused/stupid about it now.

If someone has created a page with Elementor, for example, can he/she fetch it into Frontity?
----

(pieces of a Slack conversations)
- I’m not quite sure myself. I think Luis David or Mario might know a bit better!
...
- Pages built with page builders like `Elementor`, `Page Builder by SiteOrigin`, `CoBlocks` and the likes can be fetched into Frontity apps. However, like we do with Gutenberg in [frontity.org](http://frontity.org/), you'd need to import the builder's styles into the Frontity application.In [frontity.org](http://frontity.org/), we saved the Gutenberg styles in a folders, imported it and included it with the `<Global />` component in Frontity.I was able to test this with Elementor and it worked. I'm also trying it out with other builders.NB: Using other builders does not also limit the use of Frontity features like Processors e.t.c
- I was able to test this with Elementor and it worked. I’m also trying it out with other builders.
- Does Elementor output somehow nice HTML then? Can their blocks be identified with HTML to React?
-  I guess that we can say then that Frontity is compatible with some page builders, right? To import the styles would users need a package, like the `@frontity/gutenberg` one?
- Elementor outputs nice HTML similar to Gutenberg. The elements comes with class names which can be used to style in Frontity. Frontity is compatible with most page builders. To use the page builders styles in Frontity, you'd have to copy the css files from the plugin directory into your Frontity project. In the case of Elementor, the styles can be found in `wp-content/plugins/elementor/assets/css` folder. The location of the css files in the page builders plugin might differ from the other, depending on how the plugin's folder is structured.
- How do you mean my "identified"?
- with a class name or any other HTML attribute

**Comment by juanmaguitar** [comment]
https://community.frontity.org/t/elementor-plugin-support-with-frontity/2390

**Comment by juanmaguitar** [comment]
Create a guide about how to use provessors and why they're useful when dealing with HTML created with tools such as Gutenberf, Elementor, ...

https://frontity.org/blog/connecting-gutenberg-and-frontity/
https://tutorial.frontity.org/part7-finishing-touches/use-the-html2react-component

**Comment by mburridge** [comment]
https://github.com/frontity/docs/pull/326 merged.
