### ISSUE TITLE
Create an official frontity tutorial

### ISSUE THREAD

**Issue by juanmaguitar** [frontity/docs#128]
Michal created this discussion to create a "zero to production" tutorial.

[https://community.frontity.org/t/create-an-official-frontity-tutorial/963](https://community.frontity.org/t/create-an-official-frontity-tutorial/963)

**Comment by mburridge** [comment]
This is something that might be covered by the brochure-ware blog post (which might end up being a series of posts), but we should have something similar in the docs, just after the 'Getting started' section.

**Comment by juanmaguitar** [comment]
Done! 🎉✌️
https://tutorial.frontity.org/
