### ISSUE TITLE
Document different layouts depending on category

### ISSUE THREAD

**Issue by juanmaguitar** [frontity/docs#130]
From discussion at: [https://community.frontity.org/t/moving-an-existing-wordpress-website-with-over-5000-articles/1477/23](https://community.frontity.org/t/moving-an-existing-wordpress-website-with-over-5000-articles/1477/23)

Thanks for the quick reply! In Frontity can we handle the multiple post layout depends on category?

Sure.

You could use the `[Switch` component 1](https://docs.frontity.org/api-reference-1/frontity-components#switch) for example:

```
<Switch>
  <Layout1 when={data.category === "nature"} />
  <Layout2 when={data.category === "cities"} />
  <DefaultLayout /> {/* rendered by default */}
</Switch>

```

**Comment by mburridge** [comment]
This could be a tutorial or even a blog post.

**Comment by juanmaguitar** [comment]
This is kind of covered in the tutorial.frontity.org
And this "theory"  can also be covered also in #264
