### ISSUE TITLE
Recommend ESLint for a better developer experience with Frontity

### ISSUE THREAD

**Issue by juanmaguitar** [frontity/docs#133]
Some of the issues reported in the Alexandra Spalato starter theme (console.log, unused variables, ...) could be prevented by adding a linter in our default themes.

- [https://github.com/alexadark/frontity-starter-theme/issues/1](https://github.com/alexadark/frontity-starter-theme/issues/1)
- [https://github.com/alexadark/frontity-starter-theme/issues/2](https://github.com/alexadark/frontity-starter-theme/issues/2)
- [https://github.com/alexadark/frontity-starter-theme/pull/3](https://github.com/alexadark/frontity-starter-theme/pull/3)
- [https://github.com/alexadark/frontity-starter-theme/pull/4](https://github.com/alexadark/frontity-starter-theme/pull/4)
- [https://github.com/alexadark/frontity-starter-theme/pull/5](https://github.com/alexadark/frontity-starter-theme/pull/5)
- [https://github.com/alexadark/frontity-starter-theme/pull/6](https://github.com/alexadark/frontity-starter-theme/pull/6)
- [https://github.com/alexadark/frontity-starter-theme/pull/7](https://github.com/alexadark/frontity-starter-theme/pull/7)
- [https://github.com/alexadark/frontity-starter-theme/pull/8](https://github.com/alexadark/frontity-starter-theme/pull/8)

**Comment by juanmaguitar** [comment]
Maybe some advice for creating Frontity projects would be a good idea. Here we could talk about some key ideas to be taken into account when working on a Frontity project and also suggest some thinks like this one (using a linter for the code)

@mburridge what do you think?

**Comment by mburridge** [comment]
Yes, good idea. We should make a list of the things to take into account.

**Comment by juanmaguitar** [comment]
Closing this issue as we consider it a very unimportant issue right now
