### ISSUE TITLE
Pretty permalinks

### ISSUE THREAD

**Issue by juanmaguitar** [frontity/docs#135]
It'd be good to mention in the `@frontity/wp-source` package that it only works with pretty permalinks (as opposed to plain permalinks).

This is not about Frontity itself, it's a thing of `@frontity/wp-source`. And it can be improved in the future, with either support for plain permalinks in that package or by creating a new package, for example `@frontity/wp-plain-source`.

**Comment by juanmaguitar** [comment]
Maybe a troubleshooting section under the `@frontity/wp-source` could be a good idea.
We could put there:
- this issue with pretty permalinks
- issues with WP REST API url format

**Comment by juanmaguitar** [comment]
Related to https://github.com/frontity/docs/issues/137

**Comment by mburridge** [comment]
> Maybe a troubleshooting section under the @frontity/wp-source could be a good idea.

I agree, it's a good idea 👍

**Comment by juanmaguitar** [comment]
Clarification already done at https://api.frontity.org/frontity-packages/features-packages/wp-source#how-to-use
