### ISSUE TITLE
Add Connect page

### ISSUE THREAD

**Issue by juanmaguitar** [frontity/docs#138]
Say a kind of "Recap": Okay, so far you've learnt all the concepts, let's make a recap". Frontity and its packages exposed state, actions, libraries, etc globally so components can use them using "connect", and if they are updated, all the components affected know it.

**Comment by mburridge** [comment]
Is the idea here to have a new page in the 'Learning Frontity' section, between '7. Libraries' and '8. Namespaces'?

**Comment by juanmaguitar** [comment]
Regarding `connect` we have this page → https://docs.frontity.org/api-reference-1/frontity#connect
And then this explanation under React page → https://docs.frontity.org/resources/react-basic#state-manager-frontity-connect

I think we created this to give this concept more visibility as it is one the first things you'll have to deal with whern creating a Frontity project

I think it is worth having a whole page to explain the connection of React components and the state:
- I would place that page (for now) in the [Learning Frontity](https://docs.frontity.org/learning-frontity) section
- I would move to there all the explanations that currently are in → [State Manager - Frontity Connect](https://docs.frontity.org/resources/react-basic#state-manager-frontity-connect)
- I would also explain how React components will be re-rendered when state is updated, and how we can get data by using [`actions.source.fetch()`](https://docs.frontity.org/api-reference-1/wordpress-source#actions-source-fetch) & [`state.source.get()`](https://docs.frontity.org/api-reference-1/wordpress-source#state-source-get)

**Comment by mburridge** [comment]
I agree. That section is out of place in the Key Concepts -> React section, except insofar as state managers are a common concept in React. 

I think having a dedicated page to the state manager is a good idea.

**Comment by juanmaguitar** [comment]
This content is (should be) covered in the **A Frontity Project** section of the Learning Curriculum  #264
