### ISSUE TITLE
Create a page of Frontity resources

### ISSUE THREAD

**Issue by rmartinezduque** [frontity/docs#143]
I think it would be very useful to create a page in the docs where we can collect all the posts, tutorials, workshops, talks, guides, and other resources created by us and the community.

These are some examples:

- https://strapi.io/tutorials
- https://www.gatsbyjs.org/docs/awesome-gatsby-resources/

**Comment by juanmaguitar** [comment]
@rmartinezduque Absolutely, I think this is something that should be done but this task is out of the scope of this documentation repo.

These issues are meant to keep track of the work to be done to improve our documentation site → https://docs.frontity.org/

Anyway, I'm going to let this issue here for now (but it's going to take a bit until we can do this one)

**Comment by rmartinezduque** [comment]
> These issues are meant to keep track of the work to be done to improve our documentation site → https://docs.frontity.org/.

Ops, sorry. I thought this was a task to improve our documentation site. 🙂  The more resources we have available in our docs, the better. But if you feel it doesn't fit here, please feel free to move it, yes.

**Comment by mburridge** [comment]
TBH I'm not sure it's completely out of place here as we need to create a page and populate it with content, albeit references to third-party resources.

**Comment by juanmaguitar** [comment]
I think the first step here could be adding a page in the docs so I'm removing the tag `type: no docs`

**Comment by rmartinezduque** [comment]
This is another great reference: https://reactjs.org/community/support.html. A page where they have a collection of courses, examples, events, articles, videos, podcasts, etc.

**Comment by juanmaguitar** [comment]
We close this issue as there's already a "Resources" category in the Community Forum
https://community.frontity.org/c/community/resources/15
