### ISSUE TITLE
Improve documentation regarding WP API REST urls

### ISSUE THREAD

**Issue by juanmaguitar** [frontity/docs#146]
## The rest API problem

Instead of installing WordPress on my server I tried to use a free site on worpress.com and the problem was that they don’t support the `/wp-json` endpoint. Instead, you have to use something like this:

```
https://public-api.wordpress.com/wp/v2/sites/instajuegos.home.blog/posts/ 3
```

That drove me crazy because it was so difficult to find that endpoint on forums etc. I realize that wordpress.com was very limited so I decided to install WordPress on my server. But the `/wp-json` endpoint still does not work because I didn’t have something called permalink. Again google and forums looking for the answer.

I think this is a very important part because is the way you connect your backend with your frontend. So, in my opinion, the docs are a bit poor explaining all of these cases.

_What I would do is create a small tool inside of the docs where you can type the URL of your site and then it tells you what endpoints can be used. Checking first `/wp-json` then `/?rest_route=/.` or even the wordpress.com format._

> Source: https://community.frontity.org/t/my-experience-and-some-feedback-for-frontity/999

**Comment by mburridge** [comment]
Add a note to check permalink settings in 'Initial checks' section: https://docs.frontity.org/getting-started#wordpress

**Comment by mburridge** [comment]
Added 

>Check also that you are using one of the pretty permalinks options, rather than the plain one, in Settings->Permalinks.

to `docs/getting-started/README.md`.

Added

>In particular we would like to draw your attention to the Initial checks section.

to `docs/README.md`

**Comment by juanmaguitar** [comment]
@mburridge Let's try to add links to the specific commits/PR's/issues when we adress any issue

In this case 
https://github.com/frontity/docs/commit/fbb3bc9091943daa59b0e2e3ba0006f492ab385d
for example

Also managing this with a PR would be better. 
Even if you directly merge it because there's no need to review it (but in this case I'd have liked to comment a few things)

Let's take this into account for the next one 😉
