### ISSUE TITLE
Command line options conflict

### ISSUE THREAD

**Issue by mburridge** [frontity/docs#148]
![image](https://user-images.githubusercontent.com/20643925/86265004-28711700-bbbb-11ea-8d68-7209723071c7.png)

The documentation for the command `npx frontity create` has conflicting options, `-h` can mean `theme` or `help`. 
See: https://docs.frontity.org/frontity-cli/create#options

**Comment by juanmaguitar** [comment]
Already fixed in the CLI and the docs. No more short version of option flags
