### ISSUE TITLE
Add documentation for the `<Link />` component

### ISSUE THREAD

**Issue by michalczaplinski** [frontity/docs#149]
- Code pull request: https://github.com/frontity/frontity/pull/507
- Feature Discussion: https://community.frontity.org/t/link-component/885/

The code PR contains the TSDoc which should be helpful in creating the documentation

You can see the usage of the component in the mars-theme and twenty-twenty theme in the PR linked.

**Comment by luisherranz** [comment]
@nicholasio has added another feature to the `<Link>` component, which now supports auto prefetching of the links.

- This is the new code PR: https://github.com/frontity/frontity/pull/518
- And this is the new FD: https://community.frontity.org/t/auto-prefetch-data/886

**Comment by juanmaguitar** [comment]
Fixed in https://github.com/frontity/docs/pull/205
