### ISSUE TITLE
Add documentation for the analytics library and packages

### ISSUE THREAD

**Issue by DAreRodz** [frontity/docs#151]
- Code pull request: https://github.com/frontity/frontity/pull/472
- Feature Discussions:
  - [The analytics library](https://community.frontity.org/t/the-analytics-library/1103)
  - [Comscore analytics package](https://community.frontity.org/t/comscore-analytics-package/1435)
  - [Google Analytics package](https://community.frontity.org/t/google-analytics-package/1084)
  - [Google Tag Manager package](https://community.frontity.org/t/google-tag-manager-package/1400)

This is for creating the documentation of all the analytics packages. The main package (`@frontity/analytics`) is not intented to be use as another package but extended by each specific analytics packages. I can explain that if you need so.

**Comment by juanmaguitar** [comment]
- The analytics library details are only important for developers → info will go directly in the `README.md`
- Each analytics package has a common interface that has to be documented in the docs

**Comment by juanmaguitar** [comment]
```
import Root from "./components";
import Analytics from "../types";

const analytics: Analytics = {
  roots: {
    analytics: Root,
  },
  state: {
    analytics: {
      pageviews: {},
      events: {},
    },
  },
  actions: {
    analytics: {
      // Get the functions for every analytics package
      // and run `pageview` for each one.
      pageview: ({ state, actions }) => (pageview) => {
        Object.entries(state.analytics.pageviews).forEach(
          ([namespace, shouldSend]) => {
            if (shouldSend) actions[namespace].pageview(pageview);
          }
        );
      },

      // Get the functions for every analytics package
      // and run `event` for each one.
      event: ({ state, actions }) => (event) => {
        Object.entries(state.analytics.events).forEach(
          ([namespace, shouldSend]) => {
            if (shouldSend) actions[namespace].event(event);
          }
        );
      },
    },
  },
};

export default analytics;
```

- `state.analytics.pageviews`
- `state.analytics.events`
- `actions.analytics.pageview`
- `actions.analytics.event`

### `state.analytics.pageviews`

Map of namespaces with boolean values.

This object is used by `actions.analytics.pageview` to know which
analytics packages should send the pageview to their respective
services.

If you want to disable sending pageviews for a specific analytics
package, the respective namespace of that package should be set here to
`false`.

```
pageviews: {
  googleAnalytics: false,
  comscoreAnalytics: true
}
```

**Comment by juanmaguitar** [comment]
Closed as per https://github.com/frontity/frontity/pull/573 & https://github.com/frontity/docs/pull/226
