### ISSUE TITLE
Suggest to add an "Edit in codesandbox" link in "How to share your Frontity project"

### ISSUE THREAD

**Issue by luisherranz** [frontity/docs#159]
We already have an excellent guide to instruct people how to share their Frontity project with the world: https://docs.frontity.org/guides/how-to-share-a-frontity-project

It'd be awesome if you could add a section there to instruct people to add a `sandobx.config.json` file with the `node` template like explained here https://community.frontity.org/t/update-codesandbox-template-automatically/862/3?u=luisherranz and a link to "Edit in codesandbox" in their project to make collaboration even easier.

**Comment by juanmaguitar** [comment]
Closed as proper explanation has been added to https://docs.frontity.org/guides/how-to-share-a-frontity-project
