### ISSUE TITLE
package version mismatch

### ISSUE THREAD

**Issue by mburridge** [frontity/docs#160]
I think this is a use case we didn’t think of. That users can just upgrade frontity and expect it to work. @frontity/core is not a dependency of frontity because we want to keep frontity lightweight and the users might end up with a package version mismatch like how it happened here.

@juanma I mention you here in case that it’s that something that should be more prominent in the docs. By that I mean that frontity is a modular framework that is composed of packages that need to be updated together.

https://community.frontity.org/t/error-unexpected-token-export/2307/2

**Comment by juanmaguitar** [comment]
I think this is an issue that should be solved in the product. 
By reading the post is it not clear to me if there's some solution planned or if there's some documentation needed to explain this

@DAreRodz can you shed some light on this?

**Comment by DAreRodz** [comment]
@luisherranz just opened the PR https://github.com/frontity/frontity/pull/516 to solve this issue.

That way users would know they must update `@frontity/core` as well if they only updated `frontity` package.

**Comment by juanmaguitar** [comment]
Closed as this issue has been already solved in the inner code of `@frontity/core`
https://github.com/frontity/frontity/pull/516
