### ISSUE TITLE
Fetch menu from WordPress

### ISSUE THREAD

**Issue by mburridge** [frontity/docs#167]
Create a guide in the `Guides` section on fetching a menu from WordPress.

WordPress does not expose menus in the REST API. Should we recommend installing a plugin (such as this one: https://github.com/WP-API/menus-endpoints [note: requires authentication]) to expose menus in the REST API, or demonstrate the code that would need to be added to `functions.php`?

https://community.frontity.org/t/how-to-fetch-menu-from-wordpress/415
https://community.frontity.org/t/i-have-a-problem-with-the-menu/2359/9

**Comment by Poliuk** [comment]
> Should we recommend installing a plugin (such as this one: https://github.com/WP-API/menus-endpoints [note: requires authentication]) to expose menus in the REST API, or demonstrate the code that would need to be added to functions.php?

I would cover both options

**Comment by juanmaguitar** [comment]
Closed as there's a video + demo covering this explanation 
https://github.com/frontity-demos/frontity-examples/blob/master/fetch-menu-from-wp/README.md
