### ISSUE TITLE
Remove/update old Fills documentation

### ISSUE THREAD

**Issue by mburridge** [frontity/docs#179]
The [Fills documentation in the Learning Frontity section](https://docs.frontity.org/learning-frontity/roots#fills) has been superseded by the [new Slot and Fill documentation](https://docs.frontity.org/api-reference-1/frontity#slot) so should be either removed or updated with the newer information.

**Comment by mburridge** [comment]
https://github.com/frontity/docs/pull/288

**Comment by juanmaguitar** [comment]
Closed as per #288
