### ISSUE TITLE
Remove references to @frontity/disqus-comments in the docs: Namespaces

### ISSUE THREAD

**Issue by juanmaguitar** [frontity/docs#183]
There was a `disqus-comments` package in the old Frontity PRO, but it wasn't migrated it to Frontity Framework. 
But the reference to it remained in the docs. It should be removed

https://docs.frontity.org/learning-frontity/namespaces
https://community.frontity.org/t/how-can-i-add-disqus-comments-system-to-a-blog-post/2519

**Comment by mburridge** [comment]
Done: https://docs.frontity.org/learning-frontity/namespaces#example-comments
