### ISSUE TITLE
Add a 'Convincing Others' page

### ISSUE THREAD

**Issue by mburridge** [frontity/docs#186]
As per [this page](https://www.gatsbyjs.org/docs/convincing-others/) on the Gatsby site, and [as discussed here](https://community.frontity.org/t/analysis-introducing-headless-wordpress-with-gatsby-cloud-live-preview-incremental-builds-and-more/2315/12).

**Comment by mburridge** [comment]
This should be a document for technical decision makers and influencers, e.g. senior developers, project managers, CTO's, etc...

The document should compare Frontity with other similar frameworks (Gatsby, Next) and with static solutions (Strattic) highlighting pros and cons of each to help technical decision makers in their choice of framework.

It should be neutral in tone and as unbiased as possible - it is not intended as a "sales vehicle" for Frontity.

**Comment by juanmaguitar** [comment]
Not relevant anymore
