### ISSUE TITLE
Vercel requires https

### ISSUE THREAD

**Issue by mburridge** [frontity/docs#187]
Add note to https://docs.frontity.org/deployment/deploy-using-vercel specifying that Vercel enforces https.

as per:
https://community.frontity.org/t/deploy-frontity-con-vercel/2567/5

**Comment by leerob** [comment]
Looks done, this can be closed: https://docs.frontity.org/deployment/deploy-using-vercel#vercel-and-https

**Comment by mburridge** [comment]
Thanks @leerob , issue is now closed.
