### ISSUE TITLE
Misleading documentation for selecting a theme when creating a new project

### ISSUE THREAD

**Issue by nicholasio** [frontity/docs#197]
The [documentation](https://docs.frontity.org/frontity-cli/create-commands#the-theme-option) says you can choose between `--theme mars-theme` or `--theme twentytwenty-theme` but that does not work, the cli seems to expect NPM package name even for the official themes (@frontity/twentytwenty-theme. and @frontity/mars-theme).

**Comment by juanmaguitar** [comment]
Good catch @nicholasio 
Fixed in https://github.com/frontity/docs/pull/208
You can see the final doc [here](https://docs.frontity.org/frontity-cli/create-commands#the-theme-option)
