### ISSUE TITLE
The --no-prompt option checks first for the CLI argument

### ISSUE THREAD

**Issue by luisherranz** [frontity/docs#198]
Hey guys, I've been reading the new CLI docs 🙂

In the `--no-prompt` section (https://docs.frontity.org/frontity-cli/create-commands#the-no-prompt-option) you mention that if it is used, "CLI will use the name from this FRONTITY_NAME environment variable". That is not correct, you can pass as many args as you want.

For example,

```bash
npx frontity create my-name --no-prompt
```

will use `my-name` for the project name.

It's the same for

If it doesn't work that way, it's a bug.

You can see the behaviour in this image:

![cli-arguments](https://user-images.githubusercontent.com/3305402/90607835-121e2980-e202-11ea-9db4-ce29b781f837.png)

If the CLI argument is supplied, it doesn't use the env variable.

**Comment by luisherranz** [comment]
@juanmaguitar, maybe I did not make myself clear, please accept my apologies for that. The behaviour explained in the drawing (that is now on https://docs.frontity.org/frontity-cli/environment-variables) is not exclusive to either `create` and `create-package` or `FRONTITY_NAME`. It's common to all the CLI commands.

I don't know if, by placing the explanation only inside the `FRONTITY_NAME` section and the mention of `FRONTITY_NAME` in the drawing, it will lead to the misunderstanding that that behavior is only valid for the `FRONTITY_NAME` env variable, and/or the `create` and `create-package` commands.

By the way, I've just noticed that the names of some env variables are wrong and some are missing. I'm going to do a PR to fix that. I'll let you know once it's done.

**Comment by juanmaguitar** [comment]
@luisherranz, I don't understand. 

> I don't know if, by placing the explanation only inside the FRONTITY_NAME section and the mention of FRONTITY_NAME in the drawing, it will lead to the misunderstanding that that behavior is only valid for the FRONTITY_NAME env variable, and/or the create and create-package commands.
Which other CLI Frontity commands require a "name" rather than `create` or `create-package`?

> By the way, I've just noticed that the names of some env variables are wrong and some are missing. 
I don't understand this either. In the code PR that required this documentation [I elaborated a list of Environment Variables that I specifically asked for confirmation and It seemed to be OK]( https://github.com/frontity/frontity/pull/458#issuecomment-642028577). What has changed from there?

>  I'm going to do a PR to fix that. I'll let you know once it's done.
👍

**Comment by luisherranz** [comment]
> Which other CLI Frontity commands require a "name" rather than create or create-package?

None, but the behavior of the drawing is valid for all the options, not only the "name" options.

For each option:
- It checks for a CLI arg.
- If not found, it checks for an ENV variable.
- If not found, it prompts the user if `--no-prompt` is not used.
- If `--no-prompt` is used:
  - It uses the default if it is optional.
  - It fails if it is required.

This is true for _every_ option 🙂

> In the code PR that required this documentation I elaborated a list of Environment Variables that I specifically asked for confirmation and It seemed to be OK. What has changed from there?

Those commands were right but `create` and `create-package` were wrong. I've fixed them in https://github.com/frontity/frontity/pull/545 and also added TSDocs to all the commands to help you document them.

**Comment by juanmaguitar** [comment]
>  maybe I did not make myself clear, please accept my apologies for that. The behaviour explained in the drawing (that is now on https://docs.frontity.org/frontity-cli/environment-variables) is not exclusive to either create and create-package or FRONTITY_NAME. It's common to all the CLI commands.

> I don't know if, by placing the explanation only inside the FRONTITY_NAME section and the mention of FRONTITY_NAME in the drawing, it will lead to the misunderstanding that that behavior is only valid for the FRONTITY_NAME env variable, and/or the create and create-package commands.

Oh, I see. I understand this now. You're right. The drawing explaining tho CLI works should go in a more general place

> Those commands were right but create and create-package were wrong. I've fixed them in frontity/frontity#545 and also added TSDocs to all the commands to help you document them.

OKs, then I'll review the final code to add the proper explanations

**Comment by luisherranz** [comment]
I'll open a new doc issue for that code PR 🙂

**Comment by luisherranz** [comment]
> Oh, I see. I understand this now. You're right. The drawing explaining how CLI works should go in a more general place

Sorry I didn't make myself clear before. If you need help just let me know!

**Comment by juanmaguitar** [comment]
This issue is solved in the new api.frontity.org site
https://api.frontity.org/frontity-cli#no-prompt

Once this site is properly published we can close this issue

**Comment by juanmaguitar** [comment]
Solved w/ the release of api.frontity.org 
https://api.frontity.org/frontity-cli#no-prompt
