### ISSUE TITLE
Deprecate the --publicPath CLI argument in favor of --public-path

### ISSUE THREAD

**Issue by luisherranz** [frontity/docs#202]
I made a mistake in my implementation proposal. None of our CLI args are in camelcase (--use-cwd or --no-prompt) and our commands are neither (create-package).

For that reason, I've done a PR to change `--publicPath` to `--public-path` (https://github.com/frontity/frontity/pull/541) so we need to update the docs.

I wouldn't mention `--publicPath` anymore in the docs to avoid confusion, although it's still working. I added a Deprecation message on the CLI help though.

It's not yet possible to hide an argument from the help. It seems like the commander maintainers will add this soon (tj/commander.js#1331) so we can use that in the future to omit this from the help.

**Comment by juanmaguitar** [comment]
Solved by https://github.com/frontity/docs/pull/203
