### ISSUE TITLE
Fix CLI env variable names of `create` and `create-package` commands

### ISSUE THREAD

**Issue by luisherranz** [frontity/docs#210]
I've fixed the env variable names of the `create` and `create-package` commands. Now they also contain the name of the command. From `FRONTITY_NAME` (wrong) to `FRONTITY_CREATE_NAME` (right).

I've also added TSDocs to all our CLI commands with proper explanations of the values they receive. I hope that also helps with the documentation.

This is the code PR: https://github.com/frontity/frontity/pull/545

If something is missing or you need help let me know 🙂

**Comment by luisherranz** [comment]
I've added a new commit indicating the options that will prompt if the CLI arg and the env variable is missing in case you want to add that info to the docs 🙂 https://github.com/frontity/frontity/pull/545/commits/4a598a52c1570242d6bf509d97ea20cfbef8c905

**Comment by juanmaguitar** [comment]
Issue solved by https://github.com/frontity/api-reference/pull/2
