### ISSUE TITLE
Change "Browser support" into "Requirements"

### ISSUE THREAD

**Issue by juanmaguitar** [frontity/docs#211]
Create a "Requirements" section above "About Frontity" that includes:
- The ["Browser Support"](https://docs.frontity.org/about/browser-support) section
- The [Installation requirements](https://docs.frontity.org/getting-started#installation-requirements)
- The minimum version of Node & NPM supported → https://github.com/frontity/frontity/pull/545/commits/e48c7d00177aee5be40160589bd36a6970c5cb23

**Comment by juanmaguitar** [comment]
@mburridge What do you think about making this change?

**Comment by mburridge** [comment]
Yes, it's probably a good idea that 'requirements' are more prominently positioned in the docs

**Comment by juanmaguitar** [comment]
No longer relevant issue
