### ISSUE TITLE
Document the process of updating links in the WP content

### ISSUE THREAD

**Issue by mburridge** [frontity/docs#227]
As the main domain needs to point to the Frontity installation in decoupled mode, the WP installation needs to be on a different domain/sub-domain.

We should document how to update all the links in the WP content when the site URL is changed. As per: https://wordpress.org/support/article/moving-wordpress/

Issue raised here:
https://community.frontity.org/t/my-experience-developing-a-new-frontity-theme-and-remaking-my-blog-with-frontity/2902

**Comment by juanmaguitar** [comment]
This clarification will be covered in the Remodelation of the Architecture page as part of the Embedded Mode documentation task https://github.com/frontity/api-reference/issues/12
