### ISSUE TITLE
Explain why we expose `fetch` in frontity

### ISSUE THREAD

**Issue by luisherranz** [frontity/docs#231]
We are exposing `fetch` in the frontity package:

https://docs.frontity.org/api-reference-1/frontity#fetch-1

Maybe it'd be great to add a small explanation of why we are doing so, and why people should this over other methods.

- `window.fetch` is available in the browser, so it's a 0Kb dependency.
- But `window.fetch` is not isomorphic because doesn't exist in Node.
- So we solve that by exporting it from `"frontity"`, which works great in the browser and the server:

  ```js
  import { fetch } from "frontity";
  ```

- Finally, we recommend the use of `fetch` in a Frontity package instead of using `axios`, `superagent`, `got` and so on, because Frontity is extensible.

  That means that a typical project will contain packages created by different developers. If each developer adds the fetching library they prefer, a Frontity app could end up with a copy of each:

  - `axios`: [13Kbs](https://bundlephobia.com/result?p=axios@0.20.0)
  - `superagent`: [32Kbs](https://bundlephobia.com/result?p=superagent@6.1.0)
  - `got`: [98Kbs](https://bundlephobia.com/result?p=got@11.7.0)
  - ...

  They quickly add up. That's not the case in a NextJS/GatsbySJ app because all the code belongs to the developer, so if he/she decides to use one library, he/she can be consistent across his/her code.

**Comment by juanmaguitar** [comment]
Done! 👍
