### ISSUE TITLE
Remove the “Pretty permalinks enabled” requirement from the docs

### ISSUE THREAD

**Issue by mburridge** [frontity/docs#249]
Change the requirement have pretty permalinks enabled here: https://docs.frontity.org/getting-started#have-pretty-permalinks-activated

Should we still make it a recommendation though?

**Comment by juanmaguitar** [comment]
> Should we still make it a recommendation though?

I think so

**Comment by juanmaguitar** [comment]
@mburridge I think we can close this issue as [it's no longer needed](https://community.frontity.org/t/are-enabled-pretty-permalinks-necessary-to-start-using-frontity/3410/11?u=juanma)

**Comment by juanmaguitar** [comment]
I'm closing the issue as it's no longer needed
