### ISSUE TITLE
Review English Isomorphic App and Env Variables

### ISSUE THREAD

**Issue by juanmaguitar** [frontity/docs#318]
https://docs.frontity.org/isomorphic-react#initialization-or-bootstraping-of-a-frontity-app
https://docs.frontity.org/guides/how-to-use-environment-variables-in-frontity

**Comment by mburridge** [comment]
@juanmaguitar https://github.com/frontity/docs/pull/321 awaiting your review

**Comment by mburridge** [comment]
@juanmaguitar https://github.com/frontity/docs/pull/322 awaiting your review.

**Comment by juanmaguitar** [comment]
Review latest section [Server-side code and Client-side code](https://docs.frontity.org/isomorphic-react#server-side-code-and-client-side-code)
