### ISSUE TITLE
Wrong `populate` example in @frontity/wp-source package

### ISSUE THREAD

**Issue by DAreRodz** [frontity/docs#87]
The example included for the [`populate`](https://docs.frontity.org/api-reference-1/wordpress-source#populate-response-state-subdirectory-force) function shows a wrong use of [`api.get`](https://docs.frontity.org/api-reference-1/wordpress-source#api-get-endpoint-params-api-iswpcom).

`api.get` is an asynchronous function and must be called using `await` to get the returned object. However, `await` is not used in the example, and that can make handlers to stop working if developers include that code in their projects. See https://github.com/frontity/frontity/issues/438

The way to fix this is just adding `await` to the `api.get` function call:

```ts
const response = await libraries.source.api.get({ endpoint: "posts" });
```

I would take the opportunity to clarify other examples as well, for example, adding `await` also to other asynchronous function calls like [`actions.source.fetch`](https://docs.frontity.org/api-reference-1/wordpress-source#source-fetch) and [`libraries.source.populate`](https://docs.frontity.org/api-reference-1/wordpress-source#populate-response-state-subdirectory-force).

**Comment by juanmaguitar** [comment]
Solved by https://github.com/frontity/docs/pull/141
